import Nav from '@components/Nav';
import Provider from '@components/Provider';
import Sign from '@app/sign_in/page';
import '@styles/global.css';

export const metadata = {
  title: 'Next Generatorize',
  description: 'Generated by Next.js',
}
 
 
export default function RootLayout({ children }) {
  return (
     <html lang="en">
       <body>
         <Provider>
           <div className='main'>
             <div className='gradient'></div>
           </div>
           <main className='app'>
             <Nav/>
             {children}
           </main>
         </Provider>
       </body>
     </html>
   )
 }





// NEXTAUTH_URL=http://localhost:3000
// NEXTAUTH_URL_INTERNAL=http://localhost:3000
// NEXTAUTH_SECRET=z9UbTsWvK0j1eoXleGbRw7rfWzpY9bGfIdreLiCmzao=
 